workspace 'WebsiteLogin'
project 'WebsiteLogin/WebsiteLogin.xcodeproj/'

platform :ios, '12.0'

abstract_target 'WhiteLabels' do
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'MfaSdk' , :podspec => 'https://github.com/miracl/mfa-client-sdk-ios/releases/download/1.0.0/MfaSdk.podspec'
    
    target 'WebsiteLogin'
end
