workspace 'WebsiteLogin'
project 'WebsiteLogin/WebsiteLogin.xcodeproj/'

platform :ios, '8.0'

abstract_target 'WhiteLabels' do
    pod 'ATMHud@dhoerl'
    pod 'AFNetworking'
    
    target 'WebsiteLogin'
end
