workspace 'WebsiteLogin'
project 'WebsiteLogin/WebsiteLogin.xcodeproj/'

platform :ios, '12.0'

abstract_target 'WhiteLabels' do
    pod 'ATMHud@dhoerl'
    pod 'AFNetworking'
    pod 'MfaSdk' , :podspec => 'https://raw.githubusercontent.com/avlaev/podtest/master/mfa_pod/MfaSdk.podspec'
    
    target 'WebsiteLogin'
end
