# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DVSSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DVSSample
  pod 'MfaSdk', :podspec => 'https://github.com/miracl/mfa-client-sdk-ios/releases/download/1.0.0/MfaSdk.podspec'
end
